
//
// Laser turret
//
#define LASER_TURRET_GUN_HEIGHT 30.0f
#define LASER_TURRET_GUN_WIDTH  10.0f

#define LASER_TURRET_RADIUS     20.0f

#define LASER_TURRET_HIT_POINTS 10

#define LASER_TURRET_PROJECTILE_RADIUS     20.0f
#define LASER_TURRET_PROJECTILE_LIFETIME   5.0f
#define LASER_TURRET_PROJECTILE_FADE_AFTER 4.8f

//
// Goon 
//
#define GOON_LEADER_COLOR  vec4(0xFF1B68E6)
#define GOON_COLOR         vec4(0xFFE6DC1E)
#define GOON_OUTLINE_COLOR BLACK_VEC4

#define GOON_LEADER_RADIUS 20.0f
#define GOON_RADIUS        15.0f
#define GOON_PADDING       5.0f
#define GOON_MOVE_SPEED    75.0f

//
// Chain circle
//
#define SMALL_CHAIN_CIRCLE  40.0f 
#define BIG_CHAIN_CIRCLE    110.0f
#define MEDIUM_CHAIN_CIRCLE 75.0f

#define CHAIN_CIRCLE_EMERGE_TIME        0.05f
#define MAX_CHAIN_CIRCLE_LIFE_TIME      2.0f
#define CHAIN_CIRCLE_LIFE_PROLONG_TIME  0.4f

//
// Score dot
//
#define SCORE_DOT_LIFETIME   12.0f
#define SCORE_DOT_FADE_AFTER 10.0f

#define SCORE_DOT_BLINK_FREQ 30.0f
#define SCORE_DOT_PULSE_FREQ 1.5f

#define SCORE_DOT_RADIUS 6.0f
#define SCORE_DOT_PULSE_TARGET_RADIUS 12.0f

//
// Colors
//
Vec4 RED_VEC4    = {1, 0, 0, 1};
Vec4 GREEN_VEC4  = {0, 1, 0, 1};
Vec4 BLUE_VEC4   = {0, 0, 1, 1};
Vec4 YELLOW_VEC4 = {1, 1, 0, 1};
Vec4 PINK_VEC4   = {1, 0, 1, 1};

Vec4 BLACK_VEC4 = {0, 0, 0, 1};
Vec4 WHITE_VEC4 = {1, 1, 1, 1};