
//
// Important vars
//
#define ASPECT_4_BY_3 1

#if ASPECT_4_BY_3
// 640×480, 800×600, 960×720, 1024×768, 1280×960
#define WINDOW_WIDTH  1024
#define WINDOW_HEIGHT 768
#else
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#endif


#define TARGET_FPS        60
#define TARGET_DELTA_TIME (1.0f/(f32)TARGET_FPS)

#define TITLE             "Arcade Jam"


#define INPUT_DELAY_TIME  0.5f

#define MAX_ENTITIES      256
#define MAX_PROJECTILES   512
#define MAX_CHAIN_CIRCLES 512
#define MAX_SCORE_DOTS    512
#define MAX_EXPLOSIONS    16


//
// Colors
//
Vec4 RED_VEC4    = {1, 0, 0, 1};
Vec4 GREEN_VEC4  = {0, 1, 0, 1};
Vec4 BLUE_VEC4   = {0, 0, 1, 1};
Vec4 YELLOW_VEC4 = {1, 1, 0, 1};
Vec4 PINK_VEC4   = {1, 0, 1, 1};

Vec4 BLACK_VEC4 = {0, 0, 0, 1};
Vec4 WHITE_VEC4 = {1, 1, 1, 1};


//
// Player
//
#define PLAYER_MOVE_SPEED     300.0f
#define PLAYER_RADIUS         10.0f
#define PLAYER_SHOOT_COOLDOWN (12*TARGET_DELTA_TIME)

#define PLAYER_HIT_POINTS     1
#define PLAYER_MAX_TURN_ANGLE (Pi32/8.0f)
#define PLAYER_TURN_SPEED     1.75f

//
// Laser turret
//
#define LASER_TURRET_GUN_HEIGHT 30.0f
#define LASER_TURRET_GUN_WIDTH  10.0f

#define LASER_TURRET_RADIUS     20.0f

#define LASER_TURRET_HIT_POINTS 10

#define LASER_TURRET_PROJECTILE_RADIUS     20.0f
#define LASER_TURRET_PROJECTILE_LIFETIME   5.0f
#define LASER_TURRET_PROJECTILE_FADE_AFTER 4.8f

//
// Triple gun turret
//
#define TRIPLE_GUN_TURRET_RADIUS 30.0f
#define TRIPLE_GUN_TURRET_COLOR  GREEN_VEC4

#define TRIPLE_GUN_TURRET_BULLET_COUNT      12
#define TRIPLE_GUN_TURRET_BULLET_RADIUS     8.0f
#define TRIPLE_GUN_TURRET_BULLET_MOVE_SPEED 115.0f
#define TRIPLE_GUN_TURRET_FIRE_RATE         1.0f/6.0f

#define TRIPLE_GUN_TURRET_GUN_ANGLE_STEP (Pi32/3.0f)
#define TRIPLE_GUN_TURRET_GUN_WIDTH  15
#define TRIPLE_GUN_TURRET_GUN_HEIGHT 20

//
// Goon 
//
#define GOON_LEADER_COLOR  vec4(0xFF1B68E6)
#define GOON_COLOR         vec4(0xFFE6DC1E)
#define GOON_OUTLINE_COLOR BLACK_VEC4

#define GOON_LEADER_RADIUS 20.0f
#define GOON_RADIUS        15.0f
#define GOON_PADDING       5.0f
#define GOON_MOVE_SPEED    50.0f

//
// Chain activator
//
#define CHAIN_ACTIVATOR_START_RADIUS   25.0f
#define CHAIN_ACTIVATOR_END_RADIUS     20.0f
#define CHAIN_ACTIVATOR_ORBITAL_RADIUS 8.0f
#define CHAIN_ACTIVATOR_MOVE_SPEED     45.0f

#define CHAIN_ACTIVATOR_START_COLOR YELLOW_VEC4
#define CHAIN_ACTIVATOR_END_COLOR   WHITE_VEC4

//
// Infector
//
#define INFECTOR_RADIUS      20.0f
#define INFECTOR_MOVE_SPEED  40.0f
#define INFECTOR_HIT_POITNS  25

//
// Chain circle
//
#define SMALL_CHAIN_CIRCLE  40.0f 
#define BIG_CHAIN_CIRCLE    110.0f
#define MEDIUM_CHAIN_CIRCLE 75.0f

#define CHAIN_CIRCLE_EMERGE_TIME        0.1f
#define MAX_CHAIN_CIRCLE_LIFE_TIME      2.0f
#define CHAIN_CIRCLE_LIFE_PROLONG_TIME  0.4f
#define CHAIN_CIRCLE_INFECTION_TIME     0.25f


//
// Score dot
//
#define SCORE_DOT_LIFETIME   12.0f
#define SCORE_DOT_FADE_AFTER 10.0f

#define SCORE_DOT_BLINK_FREQ 30.0f
#define SCORE_DOT_PULSE_FREQ 1.5f

#define SCORE_DOT_RADIUS 6.0f
#define SCORE_DOT_PULSE_TARGET_RADIUS 12.0f





